body {
    background-image: url("/resource/HacksonLibrary/img/Subtle-light-patterns-vol06-PIXEDEN/05-white-brick.png");
    background-repeat: repeat;
}

#vf-page * {
    font-family: 'ヒラギノ角ゴ ProN W3','Meiryo', 'メイリオ', sans-serif;
    font-size: 18px;
    line-height: 22px;
    color: #FFFFFF;
}

h1, h2, h3, h4, h5, h6 {
    display: block;
}

.padding {
    padding: 20px 40px;
}

.black-board {
    opacity: 0.6;
    background-color: #000000 !important;
}

.input-small {
    width: 40% !important;
}

.input-medium {
    width: 60% !important;
}

.input-large {
    width: 100% !important;
}

.input-small,
.input-medium,
.input-large {
    color: #000000 !important;
}

.input-form-title {
    font-size: 22px;
    font-weight: bold;
    padding-bottom: 2px;
    margin-bottom: 10px;
    border-bottom: 3px solid #FFFFFF;
}

.btn-full-size {
    width: 100%;
}

.display-none {
    display: none;
}